# Generated by Django 4.2.7 on 2024-07-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarsBahosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(choices=[('yoqdi', 'yoqdi'), ('yoqmadi', 'yoqmadi')], max_length=10)),
                ('dars_bahosi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dars')),
            ],
        ),
        migrations.DeleteModel(
            name='DarsBaholash',
        ),
    ]
