# Generated by Django 4.2.7 on 2024-07-14 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_name_remove_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izoh',
            old_name='created_by',
            new_name='muallif',
        ),
        migrations.AddField(
            model_name='darsbahosi',
            name='muallif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
