# Generated by Django 5.0.7 on 2024-07-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dars_dars_videosi_delete_darsvideosi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izoh',
            name='muallif',
        ),
    ]
