# Generated by Django 5.0.7 on 2024-07-15 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_liketext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dars',
            name='dars_videosi',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'AVI', 'MVB'])]),
        ),
    ]
