# Generated by Django 5.0.7 on 2024-07-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_dars_dars_videosi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liketext',
            old_name='text_model',
            new_name='dars_like',
        ),
    ]
