# Generated by Django 5.0.7 on 2024-07-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_liketext_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeText',
            new_name='LikeBosish',
        ),
    ]
