# Generated by Django 5.0.7 on 2024-07-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_liketext_likebosish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likebosish',
            old_name='created',
            new_name='created_by',
        ),
        migrations.DeleteModel(
            name='DarsBahosi',
        ),
    ]
